development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || Rails.application.credentials.production[:redis_url] || 'redis://localhost:6379/1' %>
  channel_prefix: danmu_classroom_production
